project_id = "igvhcnqylqjfnilsvssi"

[functions.send-booking-email]
verify_jwt = false

[functions.get-available-slots]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false